- id: ty
  name: ty
  description: "Run 'ty check' for extremely fast Python type checking"
  entry: ty check
  language: python
  additional_dependencies:
    - ty
    - .
  pass_filenames: false
  require_serial: true
  minimum_pre_commit_version: "2.9.2"
